// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using estore.Models;

namespace estore.Migrations
{
    [DbContext(typeof(productContext))]
    [Migration("20220805163547_product Description")]
    partial class productDescription
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("estore.Models.product", b =>
                {
                    b.Property<int>("productID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("discount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("inConfomation")
                        .HasColumnType("bit");

                    b.Property<bool>("isAddedToCart")
                        .HasColumnType("bit");

                    b.Property<bool>("isAddedToCheckout")
                        .HasColumnType("bit");

                    b.Property<bool>("isBestCollection")
                        .HasColumnType("bit");

                    b.Property<bool>("isBestProduct")
                        .HasColumnType("bit");

                    b.Property<bool>("isCategory")
                        .HasColumnType("bit");

                    b.Property<bool>("isLatestOffer")
                        .HasColumnType("bit");

                    b.Property<bool>("isLatestProduct")
                        .HasColumnType("bit");

                    b.Property<bool>("isSlider")
                        .HasColumnType("bit");

                    b.Property<bool>("isgallery")
                        .HasColumnType("bit");

                    b.Property<string>("price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("productID");

                    b.ToTable("products");
                });
#pragma warning restore 612, 618
        }
    }
}
